name: Checks

on: [push, pull_request]

jobs:
  Test:
    strategy:
      fail-fast: false
    runs-on:  macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: List changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
      - name: Install repository
        run: |
          brew tap mediaarea/homebrew-mediaarea $PWD
      - name: Check
        run: |
            for file in ${{ steps.changed-files.outputs.added_modified }} ; do
                if [[  "${file##*.}" != "rb" ]] ; then
                    continue
                fi
                formula=$(basename -s .rb $file)
                if [[ "$(dirname $file)" == "Casks" ]] ; then
                    brew install --cask $formula
                    brew cask audit --download $formula
                    brew cask style --fix $formula
                else
                    brew install $formula
                    brew audit --strict $formula
                fi
            done
